// GENERATED by tools/gen_import_stubs.py — do not edit by hand.
//
// Honest-failure stubs for the 153 of this image's 244 kernel imports
// that have no implementation yet (91 are real, in
// runtime/kernel/imports.cpp). Each logs its name through the same [kcall]
// trace the implemented imports use — so the phase gates see the complete
// first-occurrence sequence — then returns STATUS_NOT_IMPLEMENTED rather
// than faking success.
//
// A generated stub has no signature and therefore CANNOT zero-fill an
// out-parameter. Read the generator's docstring before treating that as a
// bug to patch here: the fix for any import whose out-parameter the guest
// actually reads is a real GUEST_FUNCTION_HOOK in imports.cpp, not a
// cleverer stub.

#include <ppc_config.h>   // ppc_context.h #errors without it
#include <ppc_context.h>

#include "klog.h"

// STATUS_NOT_IMPLEMENTED. Spelled out rather than included from kobject.h so
// this file stays buildable on its own at any phase.
#define CZ_UNIMPLEMENTED_IMPORT 0xC0000002u

PPC_FUNC(__imp__XNotifyGetNext) {
    KCALL("XNotifyGetNext");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamContentCreateEx) {
    KCALL("XamContentCreateEx");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamContentClose) {
    KCALL("XamContentClose");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamContentGetLicenseMask) {
    KCALL("XamContentGetLicenseMask");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamContentCreateEnumerator) {
    KCALL("XamContentCreateEnumerator");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamContentGetDeviceState) {
    KCALL("XamContentGetDeviceState");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamContentGetDeviceData) {
    KCALL("XamContentGetDeviceData");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XMsgStartIORequest) {
    KCALL("XMsgStartIORequest");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamInputGetCapabilities) {
    KCALL("XamInputGetCapabilities");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamInputGetState) {
    KCALL("XamInputGetState");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamInputSetState) {
    KCALL("XamInputSetState");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamInputGetKeystrokeEx) {
    KCALL("XamInputGetKeystrokeEx");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamUserGetName) {
    KCALL("XamUserGetName");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamUserGetSigninState) {
    KCALL("XamUserGetSigninState");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamUserAreUsersFriends) {
    KCALL("XamUserAreUsersFriends");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamUserCheckPrivilege) {
    KCALL("XamUserCheckPrivilege");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamGetSystemVersion) {
    KCALL("XamGetSystemVersion");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamUserCreateStatsEnumerator) {
    KCALL("XamUserCreateStatsEnumerator");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamUserGetXUID) {
    KCALL("XamUserGetXUID");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamLoaderLaunchTitle) {
    KCALL("XamLoaderLaunchTitle");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowSigninUI) {
    KCALL("XamShowSigninUI");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowFriendsUI) {
    KCALL("XamShowFriendsUI");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowPlayersUI) {
    KCALL("XamShowPlayersUI");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowMessagesUI) {
    KCALL("XamShowMessagesUI");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowGamerCardUIForXUID) {
    KCALL("XamShowGamerCardUIForXUID");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowAchievementsUI) {
    KCALL("XamShowAchievementsUI");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowMarketplaceUI) {
    KCALL("XamShowMarketplaceUI");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowDeviceSelectorUI) {
    KCALL("XamShowDeviceSelectorUI");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowMessageComposeUI) {
    KCALL("XamShowMessageComposeUI");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowFriendRequestUI) {
    KCALL("XamShowFriendRequestUI");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowDirtyDiscErrorUI) {
    KCALL("XamShowDirtyDiscErrorUI");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamNotifyCreateListener) {
    KCALL("XamNotifyCreateListener");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamUserGetSigninInfo) {
    KCALL("XamUserGetSigninInfo");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XMsgCancelIORequest) {
    KCALL("XMsgCancelIORequest");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamEnumerate) {
    KCALL("XamEnumerate");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamGetExecutionId) {
    KCALL("XamGetExecutionId");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamGetOverlappedResult) {
    KCALL("XamGetOverlappedResult");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamTaskSchedule) {
    KCALL("XamTaskSchedule");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XMsgCompleteIORequest) {
    KCALL("XMsgCompleteIORequest");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XMsgInProcessCall) {
    KCALL("XMsgInProcessCall");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamGetPrivateEnumStructureFromHandle) {
    KCALL("XamGetPrivateEnumStructureFromHandle");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamShowMessageBoxUIEx) {
    KCALL("XamShowMessageBoxUIEx");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamLoaderTerminateTitle) {
    KCALL("XamLoaderTerminateTitle");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtSetInformationFile) {
    KCALL("NtSetInformationFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtOpenFile) {
    KCALL("NtOpenFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__MmQueryStatistics) {
    KCALL("MmQueryStatistics");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtCreateFile) {
    KCALL("NtCreateFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtWriteFile) {
    KCALL("NtWriteFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp____C_specific_handler) {
    KCALL("__C_specific_handler");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtQueryFullAttributesFile) {
    KCALL("NtQueryFullAttributesFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtQueryInformationFile) {
    KCALL("NtQueryInformationFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtQueryVolumeInformationFile) {
    KCALL("NtQueryVolumeInformationFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtQueryDirectoryFile) {
    KCALL("NtQueryDirectoryFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtReadFileScatter) {
    KCALL("NtReadFileScatter");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtReadFile) {
    KCALL("NtReadFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetStartup) {
    KCALL("NetDll_XNetStartup");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetCleanup) {
    KCALL("NetDll_XNetCleanup");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetRandom) {
    KCALL("NetDll_XNetRandom");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetXnAddrToInAddr) {
    KCALL("NetDll_XNetXnAddrToInAddr");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetInAddrToXnAddr) {
    KCALL("NetDll_XNetInAddrToXnAddr");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetDnsLookup) {
    KCALL("NetDll_XNetDnsLookup");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetDnsRelease) {
    KCALL("NetDll_XNetDnsRelease");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetQosListen) {
    KCALL("NetDll_XNetQosListen");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetQosLookup) {
    KCALL("NetDll_XNetQosLookup");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetQosServiceLookup) {
    KCALL("NetDll_XNetQosServiceLookup");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetQosRelease) {
    KCALL("NetDll_XNetQosRelease");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_XNetGetTitleXnAddr) {
    KCALL("NetDll_XNetGetTitleXnAddr");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_WSAStartup) {
    KCALL("NetDll_WSAStartup");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_WSACleanup) {
    KCALL("NetDll_WSACleanup");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_socket) {
    KCALL("NetDll_socket");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_closesocket) {
    KCALL("NetDll_closesocket");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_shutdown) {
    KCALL("NetDll_shutdown");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_ioctlsocket) {
    KCALL("NetDll_ioctlsocket");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_setsockopt) {
    KCALL("NetDll_setsockopt");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_bind) {
    KCALL("NetDll_bind");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_connect) {
    KCALL("NetDll_connect");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_listen) {
    KCALL("NetDll_listen");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_accept) {
    KCALL("NetDll_accept");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_select) {
    KCALL("NetDll_select");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_recv) {
    KCALL("NetDll_recv");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_recvfrom) {
    KCALL("NetDll_recvfrom");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_send) {
    KCALL("NetDll_send");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_sendto) {
    KCALL("NetDll_sendto");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_inet_addr) {
    KCALL("NetDll_inet_addr");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_WSAGetLastError) {
    KCALL("NetDll_WSAGetLastError");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_WSACreateEvent) {
    KCALL("NetDll_WSACreateEvent");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_WSACloseEvent) {
    KCALL("NetDll_WSACloseEvent");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll_WSAResetEvent) {
    KCALL("NetDll_WSAResetEvent");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NetDll___WSAFDIsSet) {
    KCALL("NetDll___WSAFDIsSet");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamUserReadProfileSettings) {
    KCALL("XamUserReadProfileSettings");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamVoiceHeadsetPresent) {
    KCALL("XamVoiceHeadsetPresent");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamVoiceClose) {
    KCALL("XamVoiceClose");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamVoiceSubmitPacket) {
    KCALL("XamVoiceSubmitPacket");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamVoiceCreate) {
    KCALL("XamVoiceCreate");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamSessionRefObjByHandle) {
    KCALL("XamSessionRefObjByHandle");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamSessionCreateHandle) {
    KCALL("XamSessionCreateHandle");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamTaskShouldExit) {
    KCALL("XamTaskShouldExit");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XamTaskCloseHandle) {
    KCALL("XamTaskCloseHandle");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__KeEnableFpuExceptions) {
    KCALL("KeEnableFpuExceptions");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__RtlUnwind) {
    KCALL("RtlUnwind");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XeCryptShaInit) {
    KCALL("XeCryptShaInit");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XeCryptShaUpdate) {
    KCALL("XeCryptShaUpdate");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XeCryptShaFinal) {
    KCALL("XeCryptShaFinal");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__RtlCompareStringN) {
    KCALL("RtlCompareStringN");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtDeviceIoControlFile) {
    KCALL("NtDeviceIoControlFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XexLoadImageHeaders) {
    KCALL("XexLoadImageHeaders");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__NtFlushBuffersFile) {
    KCALL("NtFlushBuffersFile");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__IoInvalidDeviceRequest) {
    KCALL("IoInvalidDeviceRequest");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__IoCreateDevice) {
    KCALL("IoCreateDevice");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__IoDeleteDevice) {
    KCALL("IoDeleteDevice");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XeCryptSha) {
    KCALL("XeCryptSha");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__IoCompleteRequest) {
    KCALL("IoCompleteRequest");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__ObIsTitleObject) {
    KCALL("ObIsTitleObject");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__IoCheckShareAccess) {
    KCALL("IoCheckShareAccess");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__IoSetShareAccess) {
    KCALL("IoSetShareAccess");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__IoRemoveShareAccess) {
    KCALL("IoRemoveShareAccess");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__StfsControlDevice) {
    KCALL("StfsControlDevice");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__StfsCreateDevice) {
    KCALL("StfsCreateDevice");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XeKeysConsoleSignatureVerification) {
    KCALL("XeKeysConsoleSignatureVerification");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XeKeysConsolePrivateKeySign) {
    KCALL("XeKeysConsolePrivateKeySign");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__IoDismountVolume) {
    KCALL("IoDismountVolume");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__ObCreateSymbolicLink) {
    KCALL("ObCreateSymbolicLink");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__ObDeleteSymbolicLink) {
    KCALL("ObDeleteSymbolicLink");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__IoDismountVolumeByFileHandle) {
    KCALL("IoDismountVolumeByFileHandle");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdEnableDisableClockGating) {
    KCALL("VdEnableDisableClockGating");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdPersistDisplay) {
    KCALL("VdPersistDisplay");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdSwap) {
    KCALL("VdSwap");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdGetSystemCommandBuffer) {
    KCALL("VdGetSystemCommandBuffer");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdEnableRingBufferRPtrWriteBack) {
    KCALL("VdEnableRingBufferRPtrWriteBack");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdInitializeRingBuffer) {
    KCALL("VdInitializeRingBuffer");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdSetSystemCommandBufferGpuIdentifierAddress) {
    KCALL("VdSetSystemCommandBufferGpuIdentifierAddress");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdQueryVideoMode) {
    KCALL("VdQueryVideoMode");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__KeInitializeDpc) {
    KCALL("KeInitializeDpc");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdShutdownEngines) {
    KCALL("VdShutdownEngines");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdGetCurrentDisplayInformation) {
    KCALL("VdGetCurrentDisplayInformation");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdSetDisplayMode) {
    KCALL("VdSetDisplayMode");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdSetGraphicsInterruptCallback) {
    KCALL("VdSetGraphicsInterruptCallback");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdInitializeEngines) {
    KCALL("VdInitializeEngines");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdIsHSIOTrainingSucceeded) {
    KCALL("VdIsHSIOTrainingSucceeded");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdGetCurrentDisplayGamma) {
    KCALL("VdGetCurrentDisplayGamma");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdQueryVideoFlags) {
    KCALL("VdQueryVideoFlags");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdCallGraphicsNotificationRoutines) {
    KCALL("VdCallGraphicsNotificationRoutines");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdInitializeScalerCommandBuffer) {
    KCALL("VdInitializeScalerCommandBuffer");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdRetrainEDRAM) {
    KCALL("VdRetrainEDRAM");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__VdRetrainEDRAMWorker) {
    KCALL("VdRetrainEDRAMWorker");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XMsgStartIORequestEx) {
    KCALL("XMsgStartIORequestEx");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XAudioGetVoiceCategoryVolume) {
    KCALL("XAudioGetVoiceCategoryVolume");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XMACreateContext) {
    KCALL("XMACreateContext");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XMAReleaseContext) {
    KCALL("XMAReleaseContext");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XAudioSubmitRenderDriverFrame) {
    KCALL("XAudioSubmitRenderDriverFrame");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XAudioUnregisterRenderDriverClient) {
    KCALL("XAudioUnregisterRenderDriverClient");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XAudioRegisterRenderDriverClient) {
    KCALL("XAudioRegisterRenderDriverClient");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}

PPC_FUNC(__imp__XAudioGetSpeakerConfig) {
    KCALL("XAudioGetSpeakerConfig");
    ctx.r3.u64 = CZ_UNIMPLEMENTED_IMPORT;
}
