// GENERATED by tools/gen_import_stubs.py — do not edit by hand.
//
// 244 of this image's 244 kernel imports have no
// implementation yet (0 are real).
//
// PHASE 0.2 BEHAVIOUR: print the name and abort. The only question this
// phase asks is whether the image links and can be entered, so a call into
// an unimplemented kernel is a result we could not interpret anyway.
//
// This becomes WRONG at phase 1, whose gate is that our kernel-call
// *sequence* matches the A1 capture — aborting on the first unimplemented
// name makes the ordering half of that gate unobservable. Convert to
// STATUS_NOT_IMPLEMENTED returns then. Never to a success-shaped 0.

#include <ppc_config.h>
#include <ppc_context.h>
#include <cstdio>
#include <cstdlib>

namespace {
// Out-of-line so each stub is a two-instruction body rather than 244 copies
// of the printf setup.
[[noreturn]] void unimplemented_import(const char* name)
{
    std::fprintf(stderr, "\n[kernel] unimplemented import: %s\n", name);
    std::fprintf(stderr, "[kernel] phase 0.2 has no kernel; this is expected if the\n"
                         "         image is being entered rather than just linked.\n");
    std::fflush(stderr);
    std::abort();
}
}  // namespace

PPC_FUNC(__imp__XNotifyGetNext) { unimplemented_import("XNotifyGetNext"); }
PPC_FUNC(__imp__XGetVideoMode) { unimplemented_import("XGetVideoMode"); }
PPC_FUNC(__imp__XamContentCreateEx) { unimplemented_import("XamContentCreateEx"); }
PPC_FUNC(__imp__XamContentClose) { unimplemented_import("XamContentClose"); }
PPC_FUNC(__imp__XamContentGetLicenseMask) { unimplemented_import("XamContentGetLicenseMask"); }
PPC_FUNC(__imp__XamContentCreateEnumerator) { unimplemented_import("XamContentCreateEnumerator"); }
PPC_FUNC(__imp__XamContentGetDeviceState) { unimplemented_import("XamContentGetDeviceState"); }
PPC_FUNC(__imp__XamContentGetDeviceData) { unimplemented_import("XamContentGetDeviceData"); }
PPC_FUNC(__imp__XMsgStartIORequest) { unimplemented_import("XMsgStartIORequest"); }
PPC_FUNC(__imp__XamInputGetCapabilities) { unimplemented_import("XamInputGetCapabilities"); }
PPC_FUNC(__imp__XamInputGetState) { unimplemented_import("XamInputGetState"); }
PPC_FUNC(__imp__XamInputSetState) { unimplemented_import("XamInputSetState"); }
PPC_FUNC(__imp__XamInputGetKeystrokeEx) { unimplemented_import("XamInputGetKeystrokeEx"); }
PPC_FUNC(__imp__XamUserGetName) { unimplemented_import("XamUserGetName"); }
PPC_FUNC(__imp__XamUserGetSigninState) { unimplemented_import("XamUserGetSigninState"); }
PPC_FUNC(__imp__XamUserAreUsersFriends) { unimplemented_import("XamUserAreUsersFriends"); }
PPC_FUNC(__imp__XamUserCheckPrivilege) { unimplemented_import("XamUserCheckPrivilege"); }
PPC_FUNC(__imp__XamGetSystemVersion) { unimplemented_import("XamGetSystemVersion"); }
PPC_FUNC(__imp__XamUserCreateStatsEnumerator) { unimplemented_import("XamUserCreateStatsEnumerator"); }
PPC_FUNC(__imp__XamUserGetXUID) { unimplemented_import("XamUserGetXUID"); }
PPC_FUNC(__imp__XGetGameRegion) { unimplemented_import("XGetGameRegion"); }
PPC_FUNC(__imp__XamLoaderLaunchTitle) { unimplemented_import("XamLoaderLaunchTitle"); }
PPC_FUNC(__imp__XamShowSigninUI) { unimplemented_import("XamShowSigninUI"); }
PPC_FUNC(__imp__XamShowFriendsUI) { unimplemented_import("XamShowFriendsUI"); }
PPC_FUNC(__imp__XamShowPlayersUI) { unimplemented_import("XamShowPlayersUI"); }
PPC_FUNC(__imp__XamShowMessagesUI) { unimplemented_import("XamShowMessagesUI"); }
PPC_FUNC(__imp__XamShowGamerCardUIForXUID) { unimplemented_import("XamShowGamerCardUIForXUID"); }
PPC_FUNC(__imp__XamShowAchievementsUI) { unimplemented_import("XamShowAchievementsUI"); }
PPC_FUNC(__imp__XamShowMarketplaceUI) { unimplemented_import("XamShowMarketplaceUI"); }
PPC_FUNC(__imp__XamShowDeviceSelectorUI) { unimplemented_import("XamShowDeviceSelectorUI"); }
PPC_FUNC(__imp__XamShowMessageComposeUI) { unimplemented_import("XamShowMessageComposeUI"); }
PPC_FUNC(__imp__XamShowFriendRequestUI) { unimplemented_import("XamShowFriendRequestUI"); }
PPC_FUNC(__imp__XamShowDirtyDiscErrorUI) { unimplemented_import("XamShowDirtyDiscErrorUI"); }
PPC_FUNC(__imp__XamNotifyCreateListener) { unimplemented_import("XamNotifyCreateListener"); }
PPC_FUNC(__imp__XamUserGetSigninInfo) { unimplemented_import("XamUserGetSigninInfo"); }
PPC_FUNC(__imp__XMsgCancelIORequest) { unimplemented_import("XMsgCancelIORequest"); }
PPC_FUNC(__imp__XamEnumerate) { unimplemented_import("XamEnumerate"); }
PPC_FUNC(__imp__XamGetExecutionId) { unimplemented_import("XamGetExecutionId"); }
PPC_FUNC(__imp__XamAlloc) { unimplemented_import("XamAlloc"); }
PPC_FUNC(__imp__XamFree) { unimplemented_import("XamFree"); }
PPC_FUNC(__imp__XamGetOverlappedResult) { unimplemented_import("XamGetOverlappedResult"); }
PPC_FUNC(__imp__XamTaskSchedule) { unimplemented_import("XamTaskSchedule"); }
PPC_FUNC(__imp__XMsgCompleteIORequest) { unimplemented_import("XMsgCompleteIORequest"); }
PPC_FUNC(__imp__XMsgInProcessCall) { unimplemented_import("XMsgInProcessCall"); }
PPC_FUNC(__imp__XamGetPrivateEnumStructureFromHandle) { unimplemented_import("XamGetPrivateEnumStructureFromHandle"); }
PPC_FUNC(__imp__XamShowMessageBoxUIEx) { unimplemented_import("XamShowMessageBoxUIEx"); }
PPC_FUNC(__imp__XGetLanguage) { unimplemented_import("XGetLanguage"); }
PPC_FUNC(__imp__XGetAVPack) { unimplemented_import("XGetAVPack"); }
PPC_FUNC(__imp__XamLoaderTerminateTitle) { unimplemented_import("XamLoaderTerminateTitle"); }
PPC_FUNC(__imp__RtlTimeToTimeFields) { unimplemented_import("RtlTimeToTimeFields"); }
PPC_FUNC(__imp__KeQuerySystemTime) { unimplemented_import("KeQuerySystemTime"); }
PPC_FUNC(__imp__NtClose) { unimplemented_import("NtClose"); }
PPC_FUNC(__imp__NtSetInformationFile) { unimplemented_import("NtSetInformationFile"); }
PPC_FUNC(__imp__NtOpenFile) { unimplemented_import("NtOpenFile"); }
PPC_FUNC(__imp__RtlInitAnsiString) { unimplemented_import("RtlInitAnsiString"); }
PPC_FUNC(__imp__FscSetCacheElementCount) { unimplemented_import("FscSetCacheElementCount"); }
PPC_FUNC(__imp__NtQueryVirtualMemory) { unimplemented_import("NtQueryVirtualMemory"); }
PPC_FUNC(__imp__MmQueryStatistics) { unimplemented_import("MmQueryStatistics"); }
PPC_FUNC(__imp__RtlTimeFieldsToTime) { unimplemented_import("RtlTimeFieldsToTime"); }
PPC_FUNC(__imp__NtCreateFile) { unimplemented_import("NtCreateFile"); }
PPC_FUNC(__imp__KeGetCurrentProcessType) { unimplemented_import("KeGetCurrentProcessType"); }
PPC_FUNC(__imp__RtlNtStatusToDosError) { unimplemented_import("RtlNtStatusToDosError"); }
PPC_FUNC(__imp__RtlMultiByteToUnicodeN) { unimplemented_import("RtlMultiByteToUnicodeN"); }
PPC_FUNC(__imp__ExGetXConfigSetting) { unimplemented_import("ExGetXConfigSetting"); }
PPC_FUNC(__imp__RtlUnicodeToMultiByteN) { unimplemented_import("RtlUnicodeToMultiByteN"); }
PPC_FUNC(__imp__NtCreateEvent) { unimplemented_import("NtCreateEvent"); }
PPC_FUNC(__imp__MmAllocatePhysicalMemoryEx) { unimplemented_import("MmAllocatePhysicalMemoryEx"); }
PPC_FUNC(__imp__MmSetAddressProtect) { unimplemented_import("MmSetAddressProtect"); }
PPC_FUNC(__imp__MmFreePhysicalMemory) { unimplemented_import("MmFreePhysicalMemory"); }
PPC_FUNC(__imp__MmQueryAddressProtect) { unimplemented_import("MmQueryAddressProtect"); }
PPC_FUNC(__imp__NtWaitForSingleObjectEx) { unimplemented_import("NtWaitForSingleObjectEx"); }
PPC_FUNC(__imp__NtWriteFile) { unimplemented_import("NtWriteFile"); }
PPC_FUNC(__imp__XexGetProcedureAddress) { unimplemented_import("XexGetProcedureAddress"); }
PPC_FUNC(__imp__XexGetModuleHandle) { unimplemented_import("XexGetModuleHandle"); }
PPC_FUNC(__imp__RtlImageXexHeaderField) { unimplemented_import("RtlImageXexHeaderField"); }
PPC_FUNC(__imp__ObDereferenceObject) { unimplemented_import("ObDereferenceObject"); }
PPC_FUNC(__imp__ObReferenceObjectByHandle) { unimplemented_import("ObReferenceObjectByHandle"); }
PPC_FUNC(__imp__XexCheckExecutablePrivilege) { unimplemented_import("XexCheckExecutablePrivilege"); }
PPC_FUNC(__imp__DbgPrint) { unimplemented_import("DbgPrint"); }
PPC_FUNC(__imp____C_specific_handler) { unimplemented_import("__C_specific_handler"); }
PPC_FUNC(__imp__ExFreePool) { unimplemented_import("ExFreePool"); }
PPC_FUNC(__imp__NtAllocateVirtualMemory) { unimplemented_import("NtAllocateVirtualMemory"); }
PPC_FUNC(__imp__NtFreeVirtualMemory) { unimplemented_import("NtFreeVirtualMemory"); }
PPC_FUNC(__imp__XexUnloadImage) { unimplemented_import("XexUnloadImage"); }
PPC_FUNC(__imp__XexLoadImage) { unimplemented_import("XexLoadImage"); }
PPC_FUNC(__imp__XexGetModuleSection) { unimplemented_import("XexGetModuleSection"); }
PPC_FUNC(__imp__NtQueryFullAttributesFile) { unimplemented_import("NtQueryFullAttributesFile"); }
PPC_FUNC(__imp__NtQueryInformationFile) { unimplemented_import("NtQueryInformationFile"); }
PPC_FUNC(__imp__NtQueryVolumeInformationFile) { unimplemented_import("NtQueryVolumeInformationFile"); }
PPC_FUNC(__imp__NtQueryDirectoryFile) { unimplemented_import("NtQueryDirectoryFile"); }
PPC_FUNC(__imp__NtReadFileScatter) { unimplemented_import("NtReadFileScatter"); }
PPC_FUNC(__imp__NtReadFile) { unimplemented_import("NtReadFile"); }
PPC_FUNC(__imp__NtDuplicateObject) { unimplemented_import("NtDuplicateObject"); }
PPC_FUNC(__imp__KeSetBasePriorityThread) { unimplemented_import("KeSetBasePriorityThread"); }
PPC_FUNC(__imp__KeQueryBasePriorityThread) { unimplemented_import("KeQueryBasePriorityThread"); }
PPC_FUNC(__imp__KeSetAffinityThread) { unimplemented_import("KeSetAffinityThread"); }
PPC_FUNC(__imp__RtlLeaveCriticalSection) { unimplemented_import("RtlLeaveCriticalSection"); }
PPC_FUNC(__imp__RtlEnterCriticalSection) { unimplemented_import("RtlEnterCriticalSection"); }
PPC_FUNC(__imp__HalReturnToFirmware) { unimplemented_import("HalReturnToFirmware"); }
PPC_FUNC(__imp__RtlFillMemoryUlong) { unimplemented_import("RtlFillMemoryUlong"); }
PPC_FUNC(__imp__KeBugCheckEx) { unimplemented_import("KeBugCheckEx"); }
PPC_FUNC(__imp__RtlCompareMemoryUlong) { unimplemented_import("RtlCompareMemoryUlong"); }
PPC_FUNC(__imp__RtlInitializeCriticalSection) { unimplemented_import("RtlInitializeCriticalSection"); }
PPC_FUNC(__imp__RtlRaiseException) { unimplemented_import("RtlRaiseException"); }
PPC_FUNC(__imp__NetDll_XNetStartup) { unimplemented_import("NetDll_XNetStartup"); }
PPC_FUNC(__imp__NetDll_XNetCleanup) { unimplemented_import("NetDll_XNetCleanup"); }
PPC_FUNC(__imp__NetDll_XNetRandom) { unimplemented_import("NetDll_XNetRandom"); }
PPC_FUNC(__imp__NetDll_XNetXnAddrToInAddr) { unimplemented_import("NetDll_XNetXnAddrToInAddr"); }
PPC_FUNC(__imp__NetDll_XNetInAddrToXnAddr) { unimplemented_import("NetDll_XNetInAddrToXnAddr"); }
PPC_FUNC(__imp__NetDll_XNetDnsLookup) { unimplemented_import("NetDll_XNetDnsLookup"); }
PPC_FUNC(__imp__NetDll_XNetDnsRelease) { unimplemented_import("NetDll_XNetDnsRelease"); }
PPC_FUNC(__imp__NetDll_XNetQosListen) { unimplemented_import("NetDll_XNetQosListen"); }
PPC_FUNC(__imp__NetDll_XNetQosLookup) { unimplemented_import("NetDll_XNetQosLookup"); }
PPC_FUNC(__imp__NetDll_XNetQosServiceLookup) { unimplemented_import("NetDll_XNetQosServiceLookup"); }
PPC_FUNC(__imp__NetDll_XNetQosRelease) { unimplemented_import("NetDll_XNetQosRelease"); }
PPC_FUNC(__imp__NetDll_XNetGetTitleXnAddr) { unimplemented_import("NetDll_XNetGetTitleXnAddr"); }
PPC_FUNC(__imp__NetDll_WSAStartup) { unimplemented_import("NetDll_WSAStartup"); }
PPC_FUNC(__imp__NetDll_WSACleanup) { unimplemented_import("NetDll_WSACleanup"); }
PPC_FUNC(__imp__NetDll_socket) { unimplemented_import("NetDll_socket"); }
PPC_FUNC(__imp__NetDll_closesocket) { unimplemented_import("NetDll_closesocket"); }
PPC_FUNC(__imp__NetDll_shutdown) { unimplemented_import("NetDll_shutdown"); }
PPC_FUNC(__imp__NetDll_ioctlsocket) { unimplemented_import("NetDll_ioctlsocket"); }
PPC_FUNC(__imp__NetDll_setsockopt) { unimplemented_import("NetDll_setsockopt"); }
PPC_FUNC(__imp__NetDll_bind) { unimplemented_import("NetDll_bind"); }
PPC_FUNC(__imp__NetDll_connect) { unimplemented_import("NetDll_connect"); }
PPC_FUNC(__imp__NetDll_listen) { unimplemented_import("NetDll_listen"); }
PPC_FUNC(__imp__NetDll_accept) { unimplemented_import("NetDll_accept"); }
PPC_FUNC(__imp__NetDll_select) { unimplemented_import("NetDll_select"); }
PPC_FUNC(__imp__NetDll_recv) { unimplemented_import("NetDll_recv"); }
PPC_FUNC(__imp__NetDll_recvfrom) { unimplemented_import("NetDll_recvfrom"); }
PPC_FUNC(__imp__NetDll_send) { unimplemented_import("NetDll_send"); }
PPC_FUNC(__imp__NetDll_sendto) { unimplemented_import("NetDll_sendto"); }
PPC_FUNC(__imp__NetDll_inet_addr) { unimplemented_import("NetDll_inet_addr"); }
PPC_FUNC(__imp__NetDll_WSAGetLastError) { unimplemented_import("NetDll_WSAGetLastError"); }
PPC_FUNC(__imp__NetDll_WSACreateEvent) { unimplemented_import("NetDll_WSACreateEvent"); }
PPC_FUNC(__imp__NetDll_WSACloseEvent) { unimplemented_import("NetDll_WSACloseEvent"); }
PPC_FUNC(__imp__NetDll_WSAResetEvent) { unimplemented_import("NetDll_WSAResetEvent"); }
PPC_FUNC(__imp__NetDll___WSAFDIsSet) { unimplemented_import("NetDll___WSAFDIsSet"); }
PPC_FUNC(__imp__XamUserReadProfileSettings) { unimplemented_import("XamUserReadProfileSettings"); }
PPC_FUNC(__imp__XamVoiceHeadsetPresent) { unimplemented_import("XamVoiceHeadsetPresent"); }
PPC_FUNC(__imp__XamVoiceClose) { unimplemented_import("XamVoiceClose"); }
PPC_FUNC(__imp__XamVoiceSubmitPacket) { unimplemented_import("XamVoiceSubmitPacket"); }
PPC_FUNC(__imp__XamVoiceCreate) { unimplemented_import("XamVoiceCreate"); }
PPC_FUNC(__imp__XamSessionRefObjByHandle) { unimplemented_import("XamSessionRefObjByHandle"); }
PPC_FUNC(__imp__XamSessionCreateHandle) { unimplemented_import("XamSessionCreateHandle"); }
PPC_FUNC(__imp__XamTaskShouldExit) { unimplemented_import("XamTaskShouldExit"); }
PPC_FUNC(__imp__XamTaskCloseHandle) { unimplemented_import("XamTaskCloseHandle"); }
PPC_FUNC(__imp__RtlTryEnterCriticalSection) { unimplemented_import("RtlTryEnterCriticalSection"); }
PPC_FUNC(__imp__KfReleaseSpinLock) { unimplemented_import("KfReleaseSpinLock"); }
PPC_FUNC(__imp__KfAcquireSpinLock) { unimplemented_import("KfAcquireSpinLock"); }
PPC_FUNC(__imp__RtlInitializeCriticalSectionAndSpinCount) { unimplemented_import("RtlInitializeCriticalSectionAndSpinCount"); }
PPC_FUNC(__imp__KeEnableFpuExceptions) { unimplemented_import("KeEnableFpuExceptions"); }
PPC_FUNC(__imp__KeBugCheck) { unimplemented_import("KeBugCheck"); }
PPC_FUNC(__imp__KeTlsAlloc) { unimplemented_import("KeTlsAlloc"); }
PPC_FUNC(__imp__KeTlsGetValue) { unimplemented_import("KeTlsGetValue"); }
PPC_FUNC(__imp__KeTlsSetValue) { unimplemented_import("KeTlsSetValue"); }
PPC_FUNC(__imp__KeTlsFree) { unimplemented_import("KeTlsFree"); }
PPC_FUNC(__imp__RtlUnwind) { unimplemented_import("RtlUnwind"); }
PPC_FUNC(__imp__NtClearEvent) { unimplemented_import("NtClearEvent"); }
PPC_FUNC(__imp__NtCancelTimer) { unimplemented_import("NtCancelTimer"); }
PPC_FUNC(__imp__NtSetEvent) { unimplemented_import("NtSetEvent"); }
PPC_FUNC(__imp__NtSetTimerEx) { unimplemented_import("NtSetTimerEx"); }
PPC_FUNC(__imp__ExTerminateThread) { unimplemented_import("ExTerminateThread"); }
PPC_FUNC(__imp__NtCreateTimer) { unimplemented_import("NtCreateTimer"); }
PPC_FUNC(__imp__ExCreateThread) { unimplemented_import("ExCreateThread"); }
PPC_FUNC(__imp__KeQueryPerformanceFrequency) { unimplemented_import("KeQueryPerformanceFrequency"); }
PPC_FUNC(__imp__XeCryptShaInit) { unimplemented_import("XeCryptShaInit"); }
PPC_FUNC(__imp__XeCryptShaUpdate) { unimplemented_import("XeCryptShaUpdate"); }
PPC_FUNC(__imp__XeCryptShaFinal) { unimplemented_import("XeCryptShaFinal"); }
PPC_FUNC(__imp__NtCreateSemaphore) { unimplemented_import("NtCreateSemaphore"); }
PPC_FUNC(__imp__NtReleaseSemaphore) { unimplemented_import("NtReleaseSemaphore"); }
PPC_FUNC(__imp__NtWaitForMultipleObjectsEx) { unimplemented_import("NtWaitForMultipleObjectsEx"); }
PPC_FUNC(__imp__RtlCompareStringN) { unimplemented_import("RtlCompareStringN"); }
PPC_FUNC(__imp__NtDeviceIoControlFile) { unimplemented_import("NtDeviceIoControlFile"); }
PPC_FUNC(__imp__XexLoadImageHeaders) { unimplemented_import("XexLoadImageHeaders"); }
PPC_FUNC(__imp___snprintf) { unimplemented_import("_snprintf"); }
PPC_FUNC(__imp__NtFlushBuffersFile) { unimplemented_import("NtFlushBuffersFile"); }
PPC_FUNC(__imp__NtResumeThread) { unimplemented_import("NtResumeThread"); }
PPC_FUNC(__imp__KeDelayExecutionThread) { unimplemented_import("KeDelayExecutionThread"); }
PPC_FUNC(__imp__IoInvalidDeviceRequest) { unimplemented_import("IoInvalidDeviceRequest"); }
PPC_FUNC(__imp__ObReferenceObject) { unimplemented_import("ObReferenceObject"); }
PPC_FUNC(__imp__IoCreateDevice) { unimplemented_import("IoCreateDevice"); }
PPC_FUNC(__imp__KeLeaveCriticalRegion) { unimplemented_import("KeLeaveCriticalRegion"); }
PPC_FUNC(__imp__IoDeleteDevice) { unimplemented_import("IoDeleteDevice"); }
PPC_FUNC(__imp__KeEnterCriticalRegion) { unimplemented_import("KeEnterCriticalRegion"); }
PPC_FUNC(__imp__KeWaitForSingleObject) { unimplemented_import("KeWaitForSingleObject"); }
PPC_FUNC(__imp__KeSetEvent) { unimplemented_import("KeSetEvent"); }
PPC_FUNC(__imp__ExAllocatePoolTypeWithTag) { unimplemented_import("ExAllocatePoolTypeWithTag"); }
PPC_FUNC(__imp__XeCryptSha) { unimplemented_import("XeCryptSha"); }
PPC_FUNC(__imp__IoCompleteRequest) { unimplemented_import("IoCompleteRequest"); }
PPC_FUNC(__imp__RtlUpcaseUnicodeChar) { unimplemented_import("RtlUpcaseUnicodeChar"); }
PPC_FUNC(__imp__ObIsTitleObject) { unimplemented_import("ObIsTitleObject"); }
PPC_FUNC(__imp__IoCheckShareAccess) { unimplemented_import("IoCheckShareAccess"); }
PPC_FUNC(__imp__IoSetShareAccess) { unimplemented_import("IoSetShareAccess"); }
PPC_FUNC(__imp__IoRemoveShareAccess) { unimplemented_import("IoRemoveShareAccess"); }
PPC_FUNC(__imp__StfsControlDevice) { unimplemented_import("StfsControlDevice"); }
PPC_FUNC(__imp__StfsCreateDevice) { unimplemented_import("StfsCreateDevice"); }
PPC_FUNC(__imp__XeKeysConsoleSignatureVerification) { unimplemented_import("XeKeysConsoleSignatureVerification"); }
PPC_FUNC(__imp__XeKeysConsolePrivateKeySign) { unimplemented_import("XeKeysConsolePrivateKeySign"); }
PPC_FUNC(__imp__IoDismountVolume) { unimplemented_import("IoDismountVolume"); }
PPC_FUNC(__imp__ObCreateSymbolicLink) { unimplemented_import("ObCreateSymbolicLink"); }
PPC_FUNC(__imp__ObDeleteSymbolicLink) { unimplemented_import("ObDeleteSymbolicLink"); }
PPC_FUNC(__imp__KeResetEvent) { unimplemented_import("KeResetEvent"); }
PPC_FUNC(__imp__ExRegisterTitleTerminateNotification) { unimplemented_import("ExRegisterTitleTerminateNotification"); }
PPC_FUNC(__imp__IoDismountVolumeByFileHandle) { unimplemented_import("IoDismountVolumeByFileHandle"); }
PPC_FUNC(__imp___vsnprintf) { unimplemented_import("_vsnprintf"); }
PPC_FUNC(__imp__VdEnableDisableClockGating) { unimplemented_import("VdEnableDisableClockGating"); }
PPC_FUNC(__imp__VdPersistDisplay) { unimplemented_import("VdPersistDisplay"); }
PPC_FUNC(__imp__VdSwap) { unimplemented_import("VdSwap"); }
PPC_FUNC(__imp__VdGetSystemCommandBuffer) { unimplemented_import("VdGetSystemCommandBuffer"); }
PPC_FUNC(__imp__KeReleaseSpinLockFromRaisedIrql) { unimplemented_import("KeReleaseSpinLockFromRaisedIrql"); }
PPC_FUNC(__imp__KeAcquireSpinLockAtRaisedIrql) { unimplemented_import("KeAcquireSpinLockAtRaisedIrql"); }
PPC_FUNC(__imp__KiApcNormalRoutineNop) { unimplemented_import("KiApcNormalRoutineNop"); }
PPC_FUNC(__imp__VdEnableRingBufferRPtrWriteBack) { unimplemented_import("VdEnableRingBufferRPtrWriteBack"); }
PPC_FUNC(__imp__VdInitializeRingBuffer) { unimplemented_import("VdInitializeRingBuffer"); }
PPC_FUNC(__imp__MmGetPhysicalAddress) { unimplemented_import("MmGetPhysicalAddress"); }
PPC_FUNC(__imp__VdSetSystemCommandBufferGpuIdentifierAddress) { unimplemented_import("VdSetSystemCommandBufferGpuIdentifierAddress"); }
PPC_FUNC(__imp__sprintf) { unimplemented_import("sprintf"); }
PPC_FUNC(__imp__VdQueryVideoMode) { unimplemented_import("VdQueryVideoMode"); }
PPC_FUNC(__imp__KeLockL2) { unimplemented_import("KeLockL2"); }
PPC_FUNC(__imp__KeUnlockL2) { unimplemented_import("KeUnlockL2"); }
PPC_FUNC(__imp__KeInitializeDpc) { unimplemented_import("KeInitializeDpc"); }
PPC_FUNC(__imp__VdShutdownEngines) { unimplemented_import("VdShutdownEngines"); }
PPC_FUNC(__imp__VdGetCurrentDisplayInformation) { unimplemented_import("VdGetCurrentDisplayInformation"); }
PPC_FUNC(__imp__VdSetDisplayMode) { unimplemented_import("VdSetDisplayMode"); }
PPC_FUNC(__imp__VdSetGraphicsInterruptCallback) { unimplemented_import("VdSetGraphicsInterruptCallback"); }
PPC_FUNC(__imp__VdInitializeEngines) { unimplemented_import("VdInitializeEngines"); }
PPC_FUNC(__imp__VdIsHSIOTrainingSucceeded) { unimplemented_import("VdIsHSIOTrainingSucceeded"); }
PPC_FUNC(__imp__VdGetCurrentDisplayGamma) { unimplemented_import("VdGetCurrentDisplayGamma"); }
PPC_FUNC(__imp__VdQueryVideoFlags) { unimplemented_import("VdQueryVideoFlags"); }
PPC_FUNC(__imp__VdCallGraphicsNotificationRoutines) { unimplemented_import("VdCallGraphicsNotificationRoutines"); }
PPC_FUNC(__imp__VdInitializeScalerCommandBuffer) { unimplemented_import("VdInitializeScalerCommandBuffer"); }
PPC_FUNC(__imp__VdRetrainEDRAM) { unimplemented_import("VdRetrainEDRAM"); }
PPC_FUNC(__imp__VdRetrainEDRAMWorker) { unimplemented_import("VdRetrainEDRAMWorker"); }
PPC_FUNC(__imp__XMsgStartIORequestEx) { unimplemented_import("XMsgStartIORequestEx"); }
PPC_FUNC(__imp__XAudioGetVoiceCategoryVolume) { unimplemented_import("XAudioGetVoiceCategoryVolume"); }
PPC_FUNC(__imp__MmMapIoSpace) { unimplemented_import("MmMapIoSpace"); }
PPC_FUNC(__imp__XMACreateContext) { unimplemented_import("XMACreateContext"); }
PPC_FUNC(__imp__XMAReleaseContext) { unimplemented_import("XMAReleaseContext"); }
PPC_FUNC(__imp__KeWaitForMultipleObjects) { unimplemented_import("KeWaitForMultipleObjects"); }
PPC_FUNC(__imp__XAudioSubmitRenderDriverFrame) { unimplemented_import("XAudioSubmitRenderDriverFrame"); }
PPC_FUNC(__imp__XAudioUnregisterRenderDriverClient) { unimplemented_import("XAudioUnregisterRenderDriverClient"); }
PPC_FUNC(__imp__XAudioRegisterRenderDriverClient) { unimplemented_import("XAudioRegisterRenderDriverClient"); }
PPC_FUNC(__imp__XAudioGetSpeakerConfig) { unimplemented_import("XAudioGetSpeakerConfig"); }
