// The GPU/CPU hand-off chain, counted end to end — the instrument phase C part 7 needs.
//
// WHY THIS EXISTS. Part 6 measured that one guest ARMING of the worker callback
// produces about three hundred ISR DELIVERIES of it on the phase C draw arm, and about
// half of one on the PM4 control arm, and that the brake changes the per-frame rate by
// ~39x while leaving that ~300x ratio untouched. The two numbers behind it came out of
// CZ_FENCE_PROBE, which is a LINE budget: every count it produces is a floor unless you
// go back and check the budget did not saturate (gotcha 109), and the two counts were
// grepped out of two different hooks' prints rather than measured.
//
// The chain has six links and each one multiplies:
//
//   arms      sub_82845BA0  the guest emits a callback-arm block: SCRATCH_REG0 = a CPU
//                           mask, SCRATCH_REG4/5 = (callback, token buffer), three
//                           WAIT_REG_MEMs, an INTERRUPT packet, a re-poison.
//   ints      the command processor REACHES that INTERRUPT packet. More ints than arms
//             means the stream carrying the block is being executed more than once.
//   isr       DeliverCommandProcessorInterrupt runs the guest ISR. More isr than ints
//             means one interrupt is addressed to several hardware threads (part 5's
//             per-CPU acknowledge) — a legitimate multiplier, and one we can now read
//             instead of inferring.
//   kicks     sub_8284AAD0, the ISR's callback: pushes ONE token-buffer pointer onto the
//             per-CPU D3D worker's job ring.
//   walks     sub_8284B568, the worker's token interpreter, walking that buffer.
//   ringsub   sub_828455C0, the walk resubmitting that stream's segments to the ring —
//             which is where the next arm block comes from, closing the loop.
//
// Splitting the ratio across those six is what says WHICH link amplifies, and no
// single-hook print can do it. Every counter here is an unconditional relaxed atomic on
// a hook that already existed, so the instrument is free and always on: the numbers are
// there on any run with CZ_RING_TRACE, including the campaign runs saved for something
// else (gotcha 95 — a long campaign leaves its gates a free control).
//
// THE DISTINCT-BUFFER COUNT IS THE POINT. Part 4 established that this loop has gain one
// BY DESIGN and converges on hardware only because the guest arms with a NEW token
// buffer every frame: the kicks generated by frame N's segments arrive carrying frame
// N+1's pointer. A pipeline while the pointer advances, a runaway the moment it stops
// (gotcha 150). So "how many distinct pointers has the whole run kicked with" is the one
// number that separates the two, and `kickRepeat` — a kick carrying the same pointer as
// the one before it — is its per-event form.
#pragma once

#include <cstdint>

struct ChainStats
{
    uint64_t arms;        // sub_82845BA0 — guest callback armings
    uint64_t isr;         // guest ISR entries, source 1 (all CPUs of the mask)
    uint64_t kicks;       // sub_8284AAD0 — worker kicks
    uint64_t kickDistinct;// distinct token-buffer pointers ever kicked (capped, see .cpp)
    uint64_t kickRepeat;  // kicks whose buffer equals the immediately preceding kick's
    uint64_t walks;       // sub_8284B568 — worker token-interpreter entries
    uint64_t drains;      // sub_8284A960 — end-of-stream sentinel handler entries
    uint64_t ringsub;     // sub_828455C0 — ring submission calls
    uint64_t ringsubEnts; // total indirect-buffer entries those calls submitted
    uint64_t segSubmit;   // sub_82845AC0 — segment submits
    uint64_t segQueued;   // ...of which forked into the worker token queue
};

// A snapshot. Not consistent across fields — they are independent relaxed counters read
// one after another — which is correct for a rate but wrong for arithmetic between two
// of them within a single tick. Every claim built on these is a ratio over a whole run.
ChainStats ChainStats_Read();

// Counted here rather than in guest_probe.cpp because the ISR delivery loop lives in
// gpu/vd.cpp and knows the CPU mask; guest_probe.cpp owns all the others.
void ChainStats_CountIsr();
