#!/bin/bash
# Compile the RT passes' HLSL into committed SPIR-V headers — two embedded arrays
# (VS and PS) per pass:
#   runtime/gpu/rt_shadow.hlsl -> rt_shadow_spv.h   the route (a) atlas trace (part 64)
#   runtime/gpu/rt_factor.hlsl -> rt_factor_spv.h   the route (b) screen-space shadow
#                                                   factor (part 65)
#
# WHY A COMMITTED GENERATED HEADER rather than a build-time compile: the runtime
# build must not depend on DXC. The only DXC on this machine lives inside the
# XenosRecomp checkout (there is no system glslang/glslc/dxc — checked in part 64),
# and making cz_runtime's CMake reach into a sibling repo for a compiler would break
# every clone that has the runtime but not the recompiler toolchain. The shader is
# ~40 lines and changes rarely; regenerating is one command:
#
#   tools/build_rt_shaders.sh
#
# Ray queries need SM 6.5 and -fspv-target-env=vulkan1.2 (SPV_KHR_ray_query).
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
XENOS=~/GithubRepo/XenosRecomp
DXC="$XENOS/thirdparty/dxc-bin/bin/x64/dxc-linux"
export LD_LIBRARY_PATH="$XENOS/thirdparty/dxc-bin/lib/x64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

build_pass() {   # <hlsl basename> <symbol prefix>
  local SRC="$ROOT/runtime/gpu/$1.hlsl"
  local OUT="$ROOT/runtime/gpu/$1_spv.h"
  "$DXC" -T vs_6_5 -E VsMain -spirv -fspv-target-env=vulkan1.2 -Fo "$TMP/vs.spv" "$SRC"
  "$DXC" -T ps_6_5 -E PsMain -spirv -fspv-target-env=vulkan1.2 -Fo "$TMP/ps.spv" "$SRC"
  python3 - "$TMP/vs.spv" "$TMP/ps.spv" "$OUT" "$1" "$2" <<'PYEOF'
import sys, struct
vs, ps, out, src, prefix = sys.argv[1:6]
def words(path):
    data = open(path, 'rb').read()
    assert len(data) % 4 == 0, path
    return struct.unpack(f'<{len(data)//4}I', data)
with open(out, 'w') as f:
    f.write(f"// GENERATED by tools/build_rt_shaders.sh from runtime/gpu/{src}.hlsl\n"
            "// — do not edit; edit the HLSL and re-run the script. See its header for\n"
            "// why this is committed rather than compiled at build time.\n"
            "#pragma once\n#include <cstdint>\n\n")
    for name, path in ((prefix + "VsSpv", vs), (prefix + "PsSpv", ps)):
        w = words(path)
        f.write(f"inline constexpr uint32_t {name}[] = {{\n")
        for i in range(0, len(w), 8):
            f.write("    " + ", ".join(f"0x{x:08x}" for x in w[i:i+8]) + ",\n")
        f.write("};\n\n")
print(f"wrote {out}")
PYEOF
}

build_pass rt_shadow kRtShadow
build_pass rt_factor kRtFactor
