#!/usr/bin/env bash
# Compile tools/drawid_ps.hlsl to SPIR-V and emit it as a C header the runtime embeds.
#
# WHY A HEADER AND NOT A FILE ON DISK: the draw-ID pass is a diagnostic that has to work
# on any checkout, including one with no shader cache built yet (assets/shader_spv/ is
# gitignored). A module loaded from disk would make the instrument fail exactly where a
# fresh clone most needs it. It is a few hundred bytes; embedding costs nothing.
#
# Uses the SAME DXC and the same flags as tools/build_shader_spv.sh, so the push-constant
# layout it produces matches the translated shaders' by construction rather than by hope.
set -euo pipefail
cd "$(dirname "$0")/.."
XENOS="${XENOS:-$HOME/GithubRepo/XenosRecomp}"
DXC="$XENOS/thirdparty/dxc-bin/bin/x64/dxc-linux"
DXCLIB="$XENOS/thirdparty/dxc-bin/lib/x64"
OUT=runtime/gpu/drawid_ps_spv.h
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

LD_LIBRARY_PATH="$DXCLIB" "$DXC" -T ps_6_0 -HV 2021 \
    -all-resources-bound -spirv -fvk-use-dx-layout -Qstrip_debug \
    -Fo "$TMP/drawid.spv" tools/drawid_ps.hlsl

python3 - "$TMP/drawid.spv" "$OUT" <<'PY'
import struct, sys
data = open(sys.argv[1], 'rb').read()
words = struct.unpack('<%dI' % (len(data) // 4), data)
with open(sys.argv[2], 'w') as f:
    f.write('// GENERATED by tools/gen_drawid_shader.sh from tools/drawid_ps.hlsl.\n'
            '// Do not edit; edit the HLSL and regenerate. See that file for what this is.\n'
            '#pragma once\n#include <cstdint>\n\n'
            'inline const uint32_t kDrawIdPixelShaderSpv[] = {\n')
    for i in range(0, len(words), 8):
        f.write('    ' + ' '.join('0x%08x,' % w for w in words[i:i + 8]) + '\n')
    f.write('};\n')
print('wrote %s (%d SPIR-V words)' % (sys.argv[2], len(words)))
PY
