#!/usr/bin/env python3
"""Generate a STUB ppc/ tree so the host runtime compiles without the game.

WHY THIS EXISTS
---------------
CI has no XEX (release-plan E.1): no runner may hold the game, so the real
generated `ppc/` (57,822 functions, 156 MB) can never exist there. But the host
runtime — the ~30 sources under runtime/ that a port actually breaks — references
guest functions by name (hooks, probes, the boot chain), so it does not even
COMPILE without something standing in for the recompiled image.

This script scans runtime/ for every `sub_XXXXXXXX` reference and emits a minimal
tree with the same four files the recompiler produces:

    ppc_config.h            the image geometry (constants of THIS XEX, restated)
    ppc_recomp_shared.h     PPC_EXTERN_FUNC declarations
    ppc_recomp.stub.cpp     a weak, empty body per referenced function, in the
                            exact alias idiom the real TUs use — so the runtime's
                            own strong PPC_FUNC hooks override them identically
    ppc_func_mapping.cpp    the address table, sorted, null-terminated

`cz_runtime --smoke` then runs against this stub image and checks what it always
checks: every generated symbol resolves and every mapping entry is sane. What a
green CI tick MEANS is therefore "the host runtime compiles and links on this
platform" — it is NOT a claim that the release builds, and the workflow says so
in its own comment.

Usage:
    python3 tools/gen_stub_ppc.py [--runtime runtime] [--out ppc]
"""
import argparse
import os
import re
import sys

# The image geometry of this XEX, as XenonRecomp writes it into ppc_config.h.
# Restated here (they are facts of the title, in CLAUDE.md's game-intel section)
# because the whole point is to run where the generated file cannot exist.
CONFIG_H = """#pragma once
#ifndef PPC_CONFIG_H_INCLUDED
#define PPC_CONFIG_H_INCLUDED

// STUB ppc_config.h — generated by tools/gen_stub_ppc.py for CI builds with no
// game image. Values match the real XEX (title ID 58410A8D).

#define PPC_IMAGE_BASE 0x82000000ull
#define PPC_IMAGE_SIZE 0xB40000ull
#define PPC_CODE_BASE 0x82150000ull
#define PPC_CODE_SIZE 0x873564ull

#endif
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--runtime", default="runtime", help="runtime source dir to scan")
    ap.add_argument("--out", default="ppc", help="directory to write the stub into")
    ap.add_argument("--xenon", default=os.path.expanduser("~/GithubRepo/XenonRecomp"),
                    help="XenonRecomp checkout supplying ppc_context.h")
    args = ap.parse_args()

    # Refuse to clobber a REAL generated tree: the real one has ppc_recomp.0.cpp,
    # the stub never does. Overwriting 156 MB of regeneratable output would only
    # cost time, but doing it silently from a CI helper is how a dev tree ends up
    # mysteriously broken.
    if os.path.exists(os.path.join(args.out, "ppc_recomp.0.cpp")):
        print(f"refusing: {args.out} holds a REAL generated ppc tree "
              "(ppc_recomp.0.cpp exists); point --out elsewhere or remove it "
              "deliberately", file=sys.stderr)
        return 1

    syms = set()
    for root, _, files in os.walk(args.runtime):
        for f in files:
            if not f.endswith((".cpp", ".h")):
                continue
            with open(os.path.join(root, f), errors="replace") as fh:
                text = fh.read()
            # NOT r"\bsub_...": there is no word boundary between "__imp__" and
            # "sub_" (underscore is a word character), so \b silently missed every
            # reference spelled only as __imp__sub_X — found as 30 link errors the
            # first time this ran against a real build.
            syms.update(re.findall(r"sub_([0-9A-F]{8})\b", text))
            # X-macro hook lists build the symbol by token pasting (sub_##addr), so
            # the address appears only as a bare hex first argument: X(82846068, ...).
            syms.update(re.findall(r"\b[A-Za-z_]\w*\(\s*([0-9A-F]{8})\s*[,)]", text))
    if not syms:
        print("no sub_XXXXXXXX references found — wrong --runtime dir?", file=sys.stderr)
        return 1

    # The bare-hex capture over-collects (masks and constants are also eight hex
    # digits), so keep only word-aligned addresses inside the code range — the only
    # thing a guest FUNCTION can be. An extra stub would be harmless to the build
    # but would put a nonsense entry in the mapping smoke then has to excuse.
    code_lo, code_hi = 0x82150000, 0x82150000 + 0x873564
    addrs = sorted(a for a in {int(s, 16) for s in syms}
                   if code_lo <= a < code_hi and a % 4 == 0)
    os.makedirs(args.out, exist_ok=True)

    # The real ppc/ carries a copy of XenonUtils/ppc_context.h (the recompile
    # command copies it in); the stub needs the same copy for the same reason —
    # PPC_DIR is the include path the TUs resolve it from.
    ctx = os.path.join(args.xenon, "XenonUtils", "ppc_context.h")
    if not os.path.isfile(ctx):
        print(f"no ppc_context.h at {ctx} — pass --xenon <XenonRecomp checkout>",
              file=sys.stderr)
        return 1
    with open(ctx, errors="replace") as fh, \
         open(os.path.join(args.out, "ppc_context.h"), "w") as out:
        out.write(fh.read())

    with open(os.path.join(args.out, "ppc_config.h"), "w") as f:
        f.write(CONFIG_H)

    with open(os.path.join(args.out, "ppc_recomp_shared.h"), "w") as f:
        f.write("#pragma once\n\n// STUB — generated by tools/gen_stub_ppc.py; "
                "see its docstring.\n\n#include \"ppc_config.h\"\n"
                "#include \"ppc_context.h\"\n\n")
        for a in addrs:
            f.write(f"PPC_EXTERN_FUNC(sub_{a:08X});\n")

    # The exact idiom of a real TU: a weak alias so any strong PPC_FUNC hook in the
    # runtime overrides the stub the same way it overrides real recompiled code.
    with open(os.path.join(args.out, "ppc_recomp.stub.cpp"), "w") as f:
        f.write("#include \"ppc_recomp_shared.h\"\n\n")
        for a in addrs:
            f.write(f"__attribute__((alias(\"__imp__sub_{a:08X}\"))) "
                    f"PPC_WEAK_FUNC(sub_{a:08X});\n"
                    f"PPC_FUNC_IMPL(__imp__sub_{a:08X}) {{}}\n\n")

    with open(os.path.join(args.out, "ppc_func_mapping.cpp"), "w") as f:
        f.write("#include \"ppc_recomp_shared.h\"\n\n"
                "PPCFuncMapping PPCFuncMappings[] = {\n")
        for a in addrs:
            f.write(f"\t{{ 0x{a:08X}, sub_{a:08X} }},\n")
        f.write("\t{ 0, nullptr }\n};\n")

    print(f"stub ppc: {len(addrs)} referenced guest functions -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
